name: CI

on:
  push:
  pull_request:

env:
  DISPLAY: ":99"

jobs:
  stable:
    name: Integration tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
      - run: mkdir -p src/generated
      - run: cargo run -p cdp-gen -- input.json src/generated
      - run: "sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &"
      - run: sudo apt-get update
      - run: sudo apt-get install chromium-browser
      - run: cargo test -- --nocapture
